### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yeyeey** [Ubalube/src#4]
**Describe the bug**
Heres the crash report: Time: 7/2/19 11:44 AM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.item.Item.setTileEntityItemStackRenderer(Lnet/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer;)V
	at com.ubalube.scifiaddon.util.handlers.RegistryHandler.createRender(RegistryHandler.java:149)
	at com.ubalube.scifiaddon.util.handlers.RegistryHandler.onModelRegister(RegistryHandler.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_RegistryHandler_onModelRegister_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1095)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:759)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.ubalube.scifiaddon.util.handlers.RegistryHandler.createRender(RegistryHandler.java:149)
	at com.ubalube.scifiaddon.util.handlers.RegistryHandler.onModelRegister(RegistryHandler.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_RegistryHandler_onModelRegister_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1095)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:759)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 429525520 bytes (409 MB) / 1742209024 bytes (1661 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4G -XX:PermSize=512m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                      | Signature                                |
	|:----- |:------------------- |:----------------- |:------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2            | minecraft.jar                               | None                                     |
	| UCH   | mcp                 | 9.42              | minecraft.jar                               | None                                     |
	| UCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.2.2611.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.2.2611      | forge-1.12.2-14.23.2.2611.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | techguns_core       | 1.12.2-1.0        | minecraft.jar                               | None                                     |
	| UCH   | mercurius_updater   | 1.0               | MercuriusUpdater-1.12.2.jar                 | None                                     |
	| UCH   | architecturecraft   | @VERSION@         | ArchitectureCraft-Mod-1.12.2.jar            | None                                     |
	| UCH   | blockcraftery       | 1.12.2-1.1.0      | Blockcraftery-Mod-1.12.2.jar                | None                                     |
	| UCH   | buildcraftlib       | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcraftcore      | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcraftbuilders  | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcrafttransport | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcraftsilicon   | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcraftcompat    | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcraftenergy    | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcraftfactory   | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | buildcraftrobotics  | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | cdm                 | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                      | None                                     |
	| UCH   | cfm                 | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                      | None                                     |
	| UCH   | chiselsandbits      | 14.22             | Chisels-and-Bits-Mod-1.12.2.jar             | None                                     |
	| UCH   | caliber             | 1.0               | diamond-caliber_v.1.1.jar                   | None                                     |
	| UCH   | mocreatures         | 10.1.0            | DrZharks MoCreatures Mod-12.0.0.jar         | None                                     |
	| UCH   | golems              | 7.0.0-beta1       | Extra-Golems-Mod-1.12.2.jar                 | None                                     |
	| UCH   | improvedbackpacks   | 1.12.2-1.2.0.2    | Improved-Backpacks-Mod-1.12.2.jar           | None                                     |
	| UCH   | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.69.845.jar             | None                                     |
	| UCH   | tlm                 | 0.0               | Lighter-1.12.2.jar                          | None                                     |
	| UCH   | lostcities          | 2.0.20            | lostcities-1.12-2.0.20.jar                  | None                                     |
	| UCH   | mcmultipart         | 2.5.3             | MCMultiPart-Mod-1.12.2.jar                  | None                                     |
	| UCH   | millenaire          | Millénaire 7.2.1  | millenaire-1.12.2-7.2.1.jar                 | None                                     |
	| UCH   | mw                  | 1.11.7.7          | Modern-Warfare-1.12.2.jar                   | None                                     |
	| UCH   | morelayers          | 1.3               | More-Layers-Mod-1.12.2.jar                  | None                                     |
	| UCH   | mo_swords           | v4                | MoSwords-Mod-1.12.2.jar                     | None                                     |
	| UCH   | techguns            | 2.0.1.1           | Techguns-Mod-1.12.2.jar                     | None                                     |
	| UCH   | torohealthmod       | 1.12.2-11         | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar | None                                     |
	| UCH   | mysticallib         | 1.12.2-1.2.1      | MysticalLib-1.12.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
Techguns Core (Techguns-Mod-1.12.2.jar)
  techguns.core.TechgunsASMTransformer
weaponlib (Modern-Warfare-1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-12.0.23 355.11.10.50.10.103' Renderer: 'NVIDIA GeForce GTX 780M OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GTX 780M OpenGL Engine GL version 2.1 NVIDIA-12.0.23 355.11.10.50.10.103, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/ZCBM+Resourcepack+1-3, file/guns resources, file/§lDefault+3D§r+High+++++++§l19w22
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
**Version**
What version of Diamond Caliber are you using
1.1
**Forge**
What version of Forge are you using?
1.12.2
**Additional Information**
Not required

**Comment by Ubalube** [comment]
This issue has been resolved in Diamond Caliber 3.0+
